// Gunakan require untuk kompatibilitas universal
// const { PrismaClient } = require('@prisma/client');

const { PrismaClient } = require('../src/generated/prisma');
const prisma = new PrismaClient();

async function main() {
  // Insert user (upsert)
  const user = await prisma.user.upsert({
    where: { email: 'demo@example.com' },
    update: {},
    create: {
      email: 'demo@example.com',
      name: 'Demo User',
    },
  });

  // Insert multiple jobs
  await prisma.job.createMany({
    data: [
      {
        userId: user.id,
        company: 'Google',
        position: 'Software Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/xyz',
        notes: 'Apply via referral from John.',
      },
      {
        userId: user.id,
        company: 'Startup XYZ',
        position: 'Frontend Developer',
        location: 'Jakarta',
        status: 'INTERVIEW',
        jobSource: 'Telegram ReactJS Group',
        jobLink: null,
        notes: 'HR contacted via WhatsApp, interview next week.',
      },
      {
        userId: user.id,
        company: 'Microsoft',
        position: 'DevOps Engineer',
        location: 'Singapore',
        status: 'REJECTED',
        jobSource: 'Website',
        jobLink: 'https://careers.microsoft.com/abc',
        notes: 'Rejection email received after 2 weeks.',
      },
      {
        userId: user.id,
        company: 'Amazon',
        position: 'Backend Engineer',
        location: 'Bali',
        status: 'APPLIED',
        jobSource: 'JobStreet',
        jobLink: 'https://jobstreet.co.id/amazon-backend',
        notes: 'Submitted portfolio along with CV.',
      },
      {
        userId: user.id,
        company: 'Tokopedia',
        position: 'Fullstack Developer',
        location: 'Jakarta',
        status: 'INTERVIEW',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/tokopedia-fullstack',
        notes: 'Interview scheduled for Monday.',
      },
      {
        userId: user.id,
        company: 'Gojek',
        position: 'Android Developer',
        location: 'Yogyakarta',
        status: 'APPLIED',
        jobSource: 'Website',
        jobLink: 'https://gojek.jobs/android',
        notes: 'Submitted on career portal.',
      },
      {
        userId: user.id,
        company: 'Shopee',
        position: 'iOS Developer',
        location: 'Surabaya',
        status: 'REJECTED',
        jobSource: 'Referral',
        jobLink: null,
        notes: 'Received rejection after final round.',
      },
      {
        userId: user.id,
        company: 'Grab',
        position: 'QA Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'Telegram QA Group',
        jobLink: null,
        notes: 'Submitted test case examples.',
      },
      {
        userId: user.id,
        company: 'Traveloka',
        position: 'Software Engineer',
        location: 'Bandung',
        status: 'INTERVIEW',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/traveloka-se',
        notes: 'Technical test pending.',
      },
      {
        userId: user.id,
        company: 'Netflix',
        position: 'Data Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'AngelList',
        jobLink: 'https://angel.co/netflix-data',
        notes: 'Interesting company culture.',
      },
      {
        userId: user.id,
        company: 'Bukalapak',
        position: 'Site Reliability Engineer',
        location: 'Jakarta',
        status: 'REJECTED',
        jobSource: 'LinkedIn',
        jobLink: null,
        notes: 'Rejection received after test.',
      },
      {
        userId: user.id,
        company: 'IBM',
        position: 'Cloud Engineer',
        location: 'Singapore',
        status: 'INTERVIEW',
        jobSource: 'Website',
        jobLink: 'https://careers.ibm.com/cloud',
        notes: 'Interview in two phases.',
      },
      {
        userId: user.id,
        company: 'Apple',
        position: 'Software Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'Company Website',
        jobLink: 'https://apple.com/careers',
        notes: 'Great brand recognition.',
      },
      {
        userId: user.id,
        company: 'Meta',
        position: 'Machine Learning Engineer',
        location: 'Remote',
        status: 'INTERVIEW',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/meta-ml',
        notes: 'Coding test next week.',
      },
      {
        userId: user.id,
        company: 'Zalora',
        position: 'DevOps Engineer',
        location: 'Kuala Lumpur',
        status: 'REJECTED',
        jobSource: 'Techinasia',
        jobLink: null,
        notes: 'No feedback received.',
      },
      {
        userId: user.id,
        company: 'BliBli',
        position: 'Frontend Developer',
        location: 'Jakarta',
        status: 'APPLIED',
        jobSource: 'Website',
        jobLink: 'https://careers.blibli.com',
        notes: 'Applied using company portal.',
      },
      {
        userId: user.id,
        company: 'DANA',
        position: 'Backend Developer',
        location: 'Jakarta',
        status: 'INTERVIEW',
        jobSource: 'Referral',
        jobLink: null,
        notes: 'Got referred by a former colleague.',
      },
      {
        userId: user.id,
        company: 'OVO',
        position: 'Data Analyst',
        location: 'Jakarta',
        status: 'APPLIED',
        jobSource: 'JobFair',
        jobLink: null,
        notes: 'Spoke to HR at event.',
      },
      {
        userId: user.id,
        company: 'Indofood',
        position: 'Business Analyst',
        location: 'Jakarta',
        status: 'REJECTED',
        jobSource: 'Company Website',
        jobLink: null,
        notes: 'Position closed.',
      },
      {
        userId: user.id,
        company: 'Ruangguru',
        position: 'Education Technology Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/ruangguru-edtech',
        notes: 'Interested in edtech.',
      },
      {
        userId: user.id,
        company: 'Tiket.com',
        position: 'Product Manager',
        location: 'Jakarta',
        status: 'INTERVIEW',
        jobSource: 'Referral',
        jobLink: null,
        notes: 'Initial interview done.',
      },
      {
        userId: user.id,
        company: 'Grab',
        position: 'UX Designer',
        location: 'Singapore',
        status: 'APPLIED',
        jobSource: 'Dribbble',
        jobLink: null,
        notes: 'Submitted portfolio link.',
      },
      {
        userId: user.id,
        company: 'Google',
        position: 'Product Designer',
        location: 'Jakarta',
        status: 'REJECTED',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/google-designer',
        notes: 'Not selected for next round.',
      },
      {
        userId: user.id,
        company: 'TikTok',
        position: 'AI Research Engineer',
        location: 'Remote',
        status: 'APPLIED',
        jobSource: 'Website',
        jobLink: 'https://careers.tiktok.com/ai',
        notes: 'Submitted resume and research paper.',
      },
      {
        userId: user.id,
        company: 'Samsung',
        position: 'Embedded Engineer',
        location: 'South Korea',
        status: 'APPLIED',
        jobSource: 'LinkedIn',
        jobLink: 'https://linkedin.com/jobs/samsung-embedded',
        notes: 'Waiting for response.',
      },
    ],
  });
}

main()
  .then(() => {
    console.log('✅ Seed completed.');
  })
  .catch((e) => {
    console.error('❌ Seed failed.', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
